/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PainelMigracaoRouteImport } from './routes/painel-migracao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppListaEsperaRouteImport } from './routes/_authenticated/app.lista-espera'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/app.financeiro'
import { Route as AuthenticatedAppEncaminhamentosRouteImport } from './routes/_authenticated/app.encaminhamentos'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppBloqueiosRouteImport } from './routes/_authenticated/app.bloqueios'
import { Route as AuthenticatedAppBibliotecaRouteImport } from './routes/_authenticated/app.biblioteca'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as AuthenticatedAppProntuariosIndexRouteImport } from './routes/_authenticated/app.prontuarios.index'
import { Route as AuthenticatedAppPacientesIndexRouteImport } from './routes/_authenticated/app.pacientes.index'
import { Route as AuthenticatedAppProntuariosIdRouteImport } from './routes/_authenticated/app.prontuarios.$id'
import { Route as AuthenticatedAppPacientesIdRouteImport } from './routes/_authenticated/app.pacientes.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelMigracaoRoute = PainelMigracaoRouteImport.update({
  id: '/painel-migracao',
  path: '/painel-migracao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppListaEsperaRoute =
  AuthenticatedAppListaEsperaRouteImport.update({
    id: '/lista-espera',
    path: '/lista-espera',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEncaminhamentosRoute =
  AuthenticatedAppEncaminhamentosRouteImport.update({
    id: '/encaminhamentos',
    path: '/encaminhamentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBloqueiosRoute =
  AuthenticatedAppBloqueiosRouteImport.update({
    id: '/bloqueios',
    path: '/bloqueios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBibliotecaRoute =
  AuthenticatedAppBibliotecaRouteImport.update({
    id: '/biblioteca',
    path: '/biblioteca',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProntuariosIndexRoute =
  AuthenticatedAppProntuariosIndexRouteImport.update({
    id: '/prontuarios/',
    path: '/prontuarios/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPacientesIndexRoute =
  AuthenticatedAppPacientesIndexRouteImport.update({
    id: '/pacientes/',
    path: '/pacientes/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProntuariosIdRoute =
  AuthenticatedAppProntuariosIdRouteImport.update({
    id: '/prontuarios/$id',
    path: '/prontuarios/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPacientesIdRoute =
  AuthenticatedAppPacientesIdRouteImport.update({
    id: '/pacientes/$id',
    path: '/pacientes/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/painel-migracao': typeof PainelMigracaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/app/bloqueios': typeof AuthenticatedAppBloqueiosRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/encaminhamentos': typeof AuthenticatedAppEncaminhamentosRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/lista-espera': typeof AuthenticatedAppListaEsperaRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/pacientes/$id': typeof AuthenticatedAppPacientesIdRoute
  '/app/prontuarios/$id': typeof AuthenticatedAppProntuariosIdRoute
  '/app/pacientes/': typeof AuthenticatedAppPacientesIndexRoute
  '/app/prontuarios/': typeof AuthenticatedAppProntuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/painel-migracao': typeof PainelMigracaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/app/bloqueios': typeof AuthenticatedAppBloqueiosRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/encaminhamentos': typeof AuthenticatedAppEncaminhamentosRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/lista-espera': typeof AuthenticatedAppListaEsperaRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/pacientes/$id': typeof AuthenticatedAppPacientesIdRoute
  '/app/prontuarios/$id': typeof AuthenticatedAppProntuariosIdRoute
  '/app/pacientes': typeof AuthenticatedAppPacientesIndexRoute
  '/app/prontuarios': typeof AuthenticatedAppProntuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/painel-migracao': typeof PainelMigracaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/_authenticated/app/bloqueios': typeof AuthenticatedAppBloqueiosRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/encaminhamentos': typeof AuthenticatedAppEncaminhamentosRoute
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/app/lista-espera': typeof AuthenticatedAppListaEsperaRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/pacientes/$id': typeof AuthenticatedAppPacientesIdRoute
  '/_authenticated/app/prontuarios/$id': typeof AuthenticatedAppProntuariosIdRoute
  '/_authenticated/app/pacientes/': typeof AuthenticatedAppPacientesIndexRoute
  '/_authenticated/app/prontuarios/': typeof AuthenticatedAppProntuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/painel-migracao'
    | '/reset-password'
    | '/app'
    | '/app/agenda'
    | '/app/biblioteca'
    | '/app/bloqueios'
    | '/app/configuracoes'
    | '/app/encaminhamentos'
    | '/app/financeiro'
    | '/app/lista-espera'
    | '/app/'
    | '/app/pacientes/$id'
    | '/app/prontuarios/$id'
    | '/app/pacientes/'
    | '/app/prontuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/painel-migracao'
    | '/reset-password'
    | '/app/agenda'
    | '/app/biblioteca'
    | '/app/bloqueios'
    | '/app/configuracoes'
    | '/app/encaminhamentos'
    | '/app/financeiro'
    | '/app/lista-espera'
    | '/app'
    | '/app/pacientes/$id'
    | '/app/prontuarios/$id'
    | '/app/pacientes'
    | '/app/prontuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/painel-migracao'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/biblioteca'
    | '/_authenticated/app/bloqueios'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/encaminhamentos'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/lista-espera'
    | '/_authenticated/app/'
    | '/_authenticated/app/pacientes/$id'
    | '/_authenticated/app/prontuarios/$id'
    | '/_authenticated/app/pacientes/'
    | '/_authenticated/app/prontuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PainelMigracaoRoute: typeof PainelMigracaoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-migracao': {
      id: '/painel-migracao'
      path: '/painel-migracao'
      fullPath: '/painel-migracao'
      preLoaderRoute: typeof PainelMigracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/lista-espera': {
      id: '/_authenticated/app/lista-espera'
      path: '/lista-espera'
      fullPath: '/app/lista-espera'
      preLoaderRoute: typeof AuthenticatedAppListaEsperaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/encaminhamentos': {
      id: '/_authenticated/app/encaminhamentos'
      path: '/encaminhamentos'
      fullPath: '/app/encaminhamentos'
      preLoaderRoute: typeof AuthenticatedAppEncaminhamentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bloqueios': {
      id: '/_authenticated/app/bloqueios'
      path: '/bloqueios'
      fullPath: '/app/bloqueios'
      preLoaderRoute: typeof AuthenticatedAppBloqueiosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/biblioteca': {
      id: '/_authenticated/app/biblioteca'
      path: '/biblioteca'
      fullPath: '/app/biblioteca'
      preLoaderRoute: typeof AuthenticatedAppBibliotecaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prontuarios/': {
      id: '/_authenticated/app/prontuarios/'
      path: '/prontuarios'
      fullPath: '/app/prontuarios/'
      preLoaderRoute: typeof AuthenticatedAppProntuariosIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pacientes/': {
      id: '/_authenticated/app/pacientes/'
      path: '/pacientes'
      fullPath: '/app/pacientes/'
      preLoaderRoute: typeof AuthenticatedAppPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prontuarios/$id': {
      id: '/_authenticated/app/prontuarios/$id'
      path: '/prontuarios/$id'
      fullPath: '/app/prontuarios/$id'
      preLoaderRoute: typeof AuthenticatedAppProntuariosIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pacientes/$id': {
      id: '/_authenticated/app/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/app/pacientes/$id'
      preLoaderRoute: typeof AuthenticatedAppPacientesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppBibliotecaRoute: typeof AuthenticatedAppBibliotecaRoute
  AuthenticatedAppBloqueiosRoute: typeof AuthenticatedAppBloqueiosRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppEncaminhamentosRoute: typeof AuthenticatedAppEncaminhamentosRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppListaEsperaRoute: typeof AuthenticatedAppListaEsperaRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppPacientesIdRoute: typeof AuthenticatedAppPacientesIdRoute
  AuthenticatedAppProntuariosIdRoute: typeof AuthenticatedAppProntuariosIdRoute
  AuthenticatedAppPacientesIndexRoute: typeof AuthenticatedAppPacientesIndexRoute
  AuthenticatedAppProntuariosIndexRoute: typeof AuthenticatedAppProntuariosIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppBibliotecaRoute: AuthenticatedAppBibliotecaRoute,
  AuthenticatedAppBloqueiosRoute: AuthenticatedAppBloqueiosRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppEncaminhamentosRoute: AuthenticatedAppEncaminhamentosRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppListaEsperaRoute: AuthenticatedAppListaEsperaRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppPacientesIdRoute: AuthenticatedAppPacientesIdRoute,
  AuthenticatedAppProntuariosIdRoute: AuthenticatedAppProntuariosIdRoute,
  AuthenticatedAppPacientesIndexRoute: AuthenticatedAppPacientesIndexRoute,
  AuthenticatedAppProntuariosIndexRoute: AuthenticatedAppProntuariosIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PainelMigracaoRoute: PainelMigracaoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
